### ISSUE TITLE
number() is returning incorrect values for a single char

### ISSUE THREAD

**Issue by muffinresearch** [braintree/card-validator#10]
If you enter '3' into `card-validator.number()` isPotentiallyValid is false. This doesn't make sense as adding a '7' and it's detected as amex.  See below a screenshot showing the issue.

![1__node](https://cloud.githubusercontent.com/assets/1514/7968055/36af0f62-0a26-11e5-9700-7afba2d8df6d.png)

## STR

```
npm install card-validator
node
```

```JavaScript
cv = require('card-validator');
// Compare the output of the following:
cv.number('4');
cv.number('3');
cv.number('37');
```

**Comment by EvanHahn** [comment]
This is a bug and we'll fix it. Good catch!
