### ISSUE TITLE
[Question]: how to add custom card brands right way?

### ISSUE THREAD

**Issue by muhammedmoussa1** [braintree/card-validator#100]
### General information

- Library version: ^8.1.0

### Issue description

I'm using `card-validator` inside react and added custom card brand always return invalid, in addition, it has a conflict with another card types. so I need to override or add the custom brand the right way, here is an example.

```
const valid = require('card-validator');

valid.creditCardType.addCard({
  niceType: 'MyCard',
  type: 'mycard',
  patterns: [XXXX],
  gaps: [4, 8, 12],
  lengths: [16],
  code: {
    name: 'CVC',
    size: 3,
  },
});


valid.creditCardType.changeOrder('meezacard', 0);
valid.creditCardType.removeCard(valid.creditCardType.types.CONFLICT);

function CardNumberField() {
  const onChange(ev) {
    const validator = valid.number(ev);
    console.log(validator);
    // Result
   { "card":{
      "niceType":"MyCard",
      "type":"mycard",
      "patterns":[XXXX],
       gaps: [4, 8, 12],
      lengths: [16],
      "code":{ "name":"CVC", "size":3},
      "matchStrength":4
    },
   "isPotentiallyValid":false,
   "isValid":false
   }}
  }
```

**Comment by crookedneighbor** [comment]
> I'm using card-validator inside react and added custom card brand always return invalid

Can you provide a full example? The code block you've put here leaves out the patterns that should match.

>  it has a conflict with another card types. so I need to override or add the custom brand the right way, here is an example.

For this, I'd utilize the `changeOrder` method on the `creditCardType` module to give your brand a higher priority than the default brand.

https://github.com/braintree/credit-card-type#adding-card-types

**Comment by muhammedmoussa1** [comment]
I updated the example and made `changeOrder` it now return the custom card fine, but still `isPotentiallyValid` and `isValid` return `false`

**Comment by crookedneighbor** [comment]
I still can't verify the behavior you are describing, because the `pattern` property is not set in your example.

**Comment by muhammedmoussa1** [comment]
yes, how can I set it correctly in case my pattern is `1234` for example? can you please add a full sample?

**Comment by crookedneighbor** [comment]
This works for me:

```js
const cv = require('card-validator');

cv.creditCardType.addCard({
  niceType: 'MyCard',
  type: 'mycard',
  patterns: [1234],
  gaps: [4, 8, 12],
  lengths: [16],
  code: {
    name: 'CVC',
    size: 3,
  },
});

cv.number('1') // { card: null, isPotentiallyValid: true, isValid: false }

cv.number('12') 
/*
{
  card: {
    niceType: 'MyCard',
    type: 'mycard',
    patterns: [ 1234 ],
    gaps: [ 4, 8, 12 ],
    lengths: [ 16 ],
    code: { name: 'CVC', size: 3 }
  },
  isPotentiallyValid: true,
  isValid: false
}
*/

// got to use a luhn valid number that is 16 digits for isValid: true
cv.number('1234123412341238') 
/*
{
  card: {
    niceType: 'MyCard',
    type: 'mycard',
    patterns: [ 1234 ],
    gaps: [ 4, 8, 12 ],
    lengths: [ 16 ],
    code: { name: 'CVC', size: 3 },
    matchStrength: 4
  },
  isPotentiallyValid: true,
  isValid: true
}
*/
```

**Comment by muhammedmoussa1** [comment]
okay, I found the issue with the number I'm using for the test, thank you.
