### ISSUE TITLE
Visa Card Length 13 is not Valid

### ISSUE THREAD

**Issue by WebPro9369** [braintree/card-validator#104]
### General information

- Library version: @latest

### Issue description

Visa card lengths is always `[16, 18, 19]`, so it doesn't allow other lengths like 13 or 14. Can you please tell me how to fix this?
Thanks!

**Comment by crookedneighbor** [comment]
I thought 13 and 14 digit visas are no longer in circulation? So they don't exist in a real world transaction. Has that changed?

**Comment by crookedneighbor** [comment]
Going to close this for now, but if you can provide documentation that indicates that Visas with length 13 and 14 are now in circulation, please post it here and we'll revisit.
