### ISSUE TITLE
Postal Code is reporting valid if entire postal code is Empty String

### ISSUE THREAD

**Issue by jplukarski** [braintree/card-validator#121]
### General information

- Library version: 9.1.0

### Issue description

Originally raised here -> https://github.com/braintree/braintree-web/issues/714

When a user submits a string with three spaces, the module reports the postal code as valid. While some postal codes do have whitespace in them (UK postal codes, for example), we should look into adding a check to see if the string contains some alpha-numeric values in them or else should be reported as invalid if the entire string is whitespace.

**Comment by jplukarski** [comment]
For internal tracking -> 125

**Comment by corydavis1** [comment]
Resolved in [10.0.0](https://github.com/braintree/card-validator/commit/f84e9c464fe0a79bd395d650b521ebae726298f0)
