### ISSUE TITLE
Use lodash base package instead of function modules

### ISSUE THREAD

**Issue by johanneslumpe** [braintree/card-validator#14]
This might be a controversial request, but I was wondering if you were inclined to change the dependencies on `lodash.assign` `lodash.isnumber` and `lodash.isstring` just to `lodash` and then require just the sub-modules, as in `var assign = require('lodash/object/assign')` etc.

The reasoning behind this is that projects which already use `lodash` as dependency will have to carry an additional weight in their payload file due to those custom lodash builds, instead of being able to utilize the same `assign`, `isNumber` and `isString` functions, which they might already be depending on anyway.

**Comment by EvanHahn** [comment]
Not a controversial request at all!

We definitely considered doing it this way but this better aligned with our needs (it's a long story!). We'd happily endorse a fork that included the full `lodash` but we're going to stick with this for now.

**Comment by EvanHahn** [comment]
We did some internal restructuring which allowed us to switch to the base lodash package. `card-validator@2.2.1` now has this!

**Comment by johanneslumpe** [comment]
Sweet @EvanHahn :+1:
