### ISSUE TITLE
Maestro validation

### ISSUE THREAD

**Issue by VonD** [braintree/card-validator#20]
Hi,

Thanks for this great lib!

There seems to be a problem with the Maestro pattern : 

```javascript
var valid = require('card-validator');
valid.number('500000000000').isPotentiallyValid // false
valid.number('5000000000000611').isPotentiallyValid // true
valid.number('5000000000000611').isValid // true
```

Many thanks

**Comment by mrak** [comment]
Thanks for the report!

Maestro cards can be length `12`, but `500000000000` is not luhn10 valid, so it reports as `isPotentiallyValid: false`.

But Maestro can be up to `19` long, so as you demonstrated it should not be decisively `isPotentiallyValid: false` with `5000000000000`

**Comment by quinnjn** [comment]
@VonD We created a pull request (#21) which should fix the problem you spotted. If you'd like to take a look at it feel free!

**Comment by VonD** [comment]
@quinnjn great! many thanks for this very quick fix!

**Comment by EvanHahn** [comment]
@VonD We've merged the fix and will do a release soon.
