### ISSUE TITLE
Using the library without building with npm

### ISSUE THREAD

**Issue by collizo4sky** [braintree/card-validator#25]
Would love to use this library as is without using npm or any other build tool. How do i use it?

Am still an old school developer that include js library in webpage header and stuff.

**Comment by collizo4sky** [comment]
Better still, a step-by-step guide on how to build the script module.

**Comment by crookedneighbor** [comment]
Thanks for your feedback @collizo4sky. You can access the browser ready file in [the dist folder](https://github.com/braintree/card-validator/tree/master/dist), which includes a minified and un-minified version. When included in a script tag in your browser, the library will be available on the `window` object as `cardValidator`. 

IE:

```js
var numberValidation = cardValidator.number('4111');

if (!numberValidation.isPotentiallyValid) {
  // logic for an invalid card number
}

if (numberValidation.card) {
  console.log(numberValidation.card.type); // 'visa'
}
```

**Comment by crookedneighbor** [comment]
I added a section to our readme describing how to use the library without a build tool: https://github.com/braintree/card-validator#loading-pre-bundled-code-in-browser

Thanks again for your feedback!

**Comment by collizo4sky** [comment]
Awesome.

**Comment by 9mm** [comment]
I no longer see a `dist` folder and I have the same question. i want to use this without having a build environment or any loaders or anything. any ideas?
