### ISSUE TITLE
Add Browserify standalone option

### ISSUE THREAD

**Issue by jeffcarp** [braintree/card-validator#3]
As suggested by @muffinresearch in https://github.com/braintree/card-validator/issues/2#issuecomment-97819472, to better support AMD and global export for browser builds, we can add a standalone namespace to our [browserify config](https://github.com/braintree/card-validator/blob/master/gulpfile.js#L35). For example:

```javascript
return browserify({
  standalone: 'card-validator',
  entries: config.src.js.main
})
```

**Comment by mrak** [comment]
Closing in favor of #6
