### ISSUE TITLE
Valid Card Holder Name?

### ISSUE THREAD

**Issue by rturk** [braintree/card-validator#33]
Add Card Holder Name validation. 

Example 
- Block non ascii characters é, á, ú, ç
- Enforce Card Holder max length 
- All UPPERCASE

**Comment by crookedneighbor** [comment]
Card holder name is not something that Braintree requires when processing a credit card, so we are not going to add this feature ourselves.

However, if anyone wants to open a pull request for this feature that includes documentation from credible sources about the requirements various processors have for valid card holder names, we're happy to include this in the API of the library.

The only thing in your list that we would consider out of scope would be the `All UPPERCASE` bullet point. That seems like an implementation detail for a virtual card ui system, not a determination about whether a card holder name is valid.

**Comment by EvanHahn** [comment]
We're going to close this issue due to inactivity. Still feel free to open a pull request and we'll take a look!

**Comment by crookedneighbor** [comment]
A validator for cardholder name has been added. It is less restrictive than one you suggested. Its basic function is to ensure that a credit card number is not accidentally entered in the cardholder name field.

Released in v8.1.0

Docs here: https://github.com/braintree/card-validator#validcardholdernamevalue-string-object
