### ISSUE TITLE
Bower integration

### ISSUE THREAD

**Issue by pensiero** [braintree/card-validator#38]
Can you put this repo also on bower? I think it will be useful for all those users who are not using npm, but only bower as package manager.

**Comment by EvanHahn** [comment]
We [still](https://github.com/braintree/card-validator/issues/22#issuecomment-182134242) have no plans to support Bower. If you'd like to maintain a fork that supports Bower, we can link to it from our readme.

**Comment by pensiero** [comment]
Sure, I think it could be an idea.
However, can I ask why? I never linked an existent project in bower but I thought it was as easy as adding a `bower.json` file inside the project

**Comment by EvanHahn** [comment]
It's not quite as easy as just adding a `bower.json` file. There's extra work required when maintaining a project to support a dependency manager that we don't use. That work includes [registering the package](https://bower.io/docs/creating-packages/#register), rebuilding the files on every release, and keeping `bower.json` in sync.

**Comment by pensiero** [comment]
👍
