### ISSUE TITLE
UMD bundle missing from npm module

### ISSUE THREAD

**Issue by trydis** [braintree/card-validator#44]
The readme says:

> You can install card-validator through npm. The npm module also includes the built, UMD bundle and its minified variant under dist/.

The dist folder is in `.npmignore` and not included in the npm module.

**Comment by skunkworks** [comment]
@trydis Thanks for opening this issue. We should have updated the README to reflect that we no longer bundle the prebuilt scripts as part of the npm package. This will be fixed shortly.

**Comment by skunkworks** [comment]
@trydis We've released [version 4.0.0](https://github.com/braintree/card-validator/blob/master/CHANGELOG.md#400), which updates the documentation to reflect that we no longer provide the built UMD bundle and only support installation via npm.
