### ISSUE TITLE
Add general check to make sure that postal codes are alphanumeric codes only

### ISSUE THREAD

**Issue by Alex-Mann** [braintree/card-validator#47]
Title explains it all. Happy to send in a PR when I get the chance.

**Comment by crookedneighbor** [comment]
Postal codes can also be rendered with a `-` or a blank space  in them, so it's not strictly alphanumeric. 

For braintree's use case, we are satisfied with the length check, but are happy to review a PR if you submit one.

**Comment by crookedneighbor** [comment]
Haven't heard anything back about this, so I'm going to close this. Feel free to still submit a PR for us to review.
