### ISSUE TITLE
isPotentiallyValid not working correctly with MC bins 222100–272099

### ISSUE THREAD

**Issue by bonpixel** [braintree/card-validator#49]
### General information

* Library version: 4.1.0
* Browser and OS: N/A but Chrome 58.0.3029.110 (64 bit) on MacOS 10.12.4 -->

### Issue description

It looks like there is an issue with `isPotentiallyValid` returning false when there could still be a match for MasterCard. In my scenario I was entering in a MC in the bin range 222100–272099 and once I entered in `27`, `isPotentiallyValid` returns `false`. If I continue to type in `7` it is still `false` but once I type `0` is is now potentially valid again. 

It seems like this shouldn't be returning false so quickly considering there are patterns that it could match. 

so again steps to reproduce ->
```javascript
var valid = require('card-validator');

var numberValidation = valid.number('27');
console.log(numberValidation.isPotentiallyValid); // false

numberValidation = valid.number('272');
console.log(numberValidation.isPotentiallyValid); // false

numberValidation = valid.number('2720');
console.log(numberValidation.isPotentiallyValid); // true
```

**Comment by crookedneighbor** [comment]
Sorry for the delay. This looks like a bug in the `credit-card-type` module. We're make the fix and update the dependency here. Thanks for reporting it!

**Comment by bonpixel** [comment]
Awesome, thanks @crookedneighbor!

**Comment by crookedneighbor** [comment]
This should be fixed now.
