### ISSUE TITLE
Type missing [@types - dt]

### ISSUE THREAD

**Issue by khalid-s** [braintree/card-validator#50]
Hi all,
Would be great if we could have a typed version of this module.

**Comment by crookedneighbor** [comment]
Braintree doesn't use Typescript, so this is not something we're going to do at this time. 

However, you can open a PR at https://github.com/chlela/DefinitelyTyped and add it yourself if you'd like.

**Comment by crookedneighbor** [comment]
This module is now written in typescript.

PR to remove it from DT: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46109
