### ISSUE TITLE
Feature request: Add custom card type

### ISSUE THREAD

**Issue by michalsindelar** [braintree/card-validator#56]
### General information

We want to this cool library in our repository. But we need to be able to specify other card types, such as `MIR` for instance.

### Issue description

I can see PR in `credit-card-type` repository with described functionality. https://github.com/braintree/credit-card-type/pull/67

Is it possible to add this functionality even to this library? 🙏

**Comment by crookedneighbor** [comment]
:+1: Here's a PR https://github.com/braintree/card-validator/pull/57

**Comment by crookedneighbor** [comment]
This has been released as part of 4.3.0

**Comment by michalsindelar** [comment]
Thank you very much 👏 👏
