### ISSUE TITLE
Question about brands

### ISSUE THREAD

**Issue by mprandot** [braintree/card-validator#68]
Hello!

I'm trying to find what brands are supported by the lib,
but i cant find in anywhere, can you help me?
To be more specific, i'm trying to find about PRESTO and MAGNA

**Comment by crookedneighbor** [comment]
Presto and Manga are not supported in the library. You can add support for them using the `addCard` method: https://github.com/braintree/card-validator/tree/858d9b28fd053173fbbaedfa1e0ad945a18793c8#custom-card-brands

**Comment by mprandot** [comment]
faaaaaaast
