### ISSUE TITLE
Request: Document the `maxElapsedYear` option

### ISSUE THREAD

**Issue by cullylarson** [braintree/card-validator#78]
Request: Add some documentation in the readme for the `maxElapsedYear` option. I had to look at the code to figure out what `maxElapsedYear` actually does. Thanks for building/maintaining this library. It looks great!

**Comment by crookedneighbor** [comment]
I just want to make sure I understand, are you looking for more clarification than what is posted here: https://github.com/braintree/card-validator#validexpirationdatevalue-stringobject-maxelapsedyear-integer-object

Maybe something like:

> The `maxElapsedYear` parameter determines how many years in the future a card's expiration date should be considered valid. It has a default value of 19, so cards with an expiration date 20 or more years in the future would not be considered valid. It can be overridden by passing in an integer as a second argument.

**Comment by cullylarson** [comment]
Exactly. As it is now, the documentation just tells you the default value for `maxElapsedYear`, but not what it actually does. Your explanation above is perfect.

**Comment by crookedneighbor** [comment]
Awesome, updated!
