### ISSUE TITLE
Broken module imports

### ISSUE THREAD

**Issue by obonyojimmy** [braintree/card-validator#82]
### General information

- Library version: React Native 
- Browser and OS : Android

### Issue description

Looks like the default export of the module is broken , so imports like `import valid from 'card-validator'` dont work any more , one has to use the named Exports ie _this works_  , `import {number, expirationDate, cvv} from 'card-validator'`.

**Comment by crookedneighbor** [comment]
👋  We're discussing in this PR whether this should be an intentional breaking change from v6 -> v7, or if we will add back in the default export: https://github.com/braintree/card-validator/pull/81

**Comment by crookedneighbor** [comment]
v7.1.0 adds in the default option, v8.0.0 switches to the `export =` syntax, so if you're using typescript, you'll need to use `"esModuleInterop": true` in your compiler options to maintain the same behavior.
