### ISSUE TITLE
Why is the "Latest" tag release listed as six years ago?

### ISSUE THREAD

**Issue by blinkybill** [braintree/card-validator#96]
There's a regular stream of great checkins to the master repo but I was confused by the date on the most recent release (being six years ago). Why is this?
Thanks!

**Comment by blinkybill** [comment]
the "Latest" tag is on version 2.2.0 which is what shows on the home page as the most recent release.

**Comment by crookedneighbor** [comment]
We just haven't been using the github releases feature, which was fine until github started putting the releases on the home page of the repo. I've added a release title to the actual latest release, so it should be showing correctly now.
