### ISSUE TITLE
Won't compile when targeting ECMAScript modules

### ISSUE THREAD

**Issue by russcarver** [braintree/card-validator#97]
### General information

- Library version: 8.1.0
- Browser and OS N/A

### Issue description

**Imported to an Angular 11 / TypeScript project as:**
import * as cardValidator from 'card-validator';
import { CardNumberVerification } from 'card-validator/src/card-number';

**Usage:**
const result: CardNumberVerification = cardValidator.number(value);

**Errors on project compilation:**
Error: node_modules/card-validator/src/card-number.ts:1:1 - error TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

1 import luhn10 = require("./luhn-10");
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/card-validator/src/card-number.ts:1:25 - error TS7016: Could not find a declaration file for module './luhn-10'. '/Users/russcarver/Code/patientpay/node_modules/card-validator/src/luhn-10.js' implicitly has an 'any' type.

1 import luhn10 = require("./luhn-10");
                          ~~~~~~~~~~~


Error: node_modules/card-validator/src/card-number.ts:2:1 - error TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

2 import getCardTypes = require("credit-card-type");

**Comment by crookedneighbor** [comment]
Importing directly from the typescript src is not officially supported. Can you do this instead?

```js
const result: ReturnType<typeof cardValidator.number> = cardValidator.number(value);
```

**Comment by russcarver** [comment]
TypeScript is the default language for Angular since version 2. This support needs to be added. We have, instead, gone with a different validator package due to this: ([https://github.com/bluestealth/credit-card-validator](https://github.com/bluestealth/credit-card-validator))

**Comment by crookedneighbor** [comment]
There's no need to reach directly into the typescript source, the compiled package includes all the type definitions necessary. We could look into exposing the types explicitly, rather than grabbing the types from the src where it's no guarantee the exact location would not change.

**Comment by russcarver** [comment]
Thanks for your insight. However, this should follow the standard import conventions that TypeScript users have come to know and love.

**Comment by crookedneighbor** [comment]
Do you have documentation around the standard import conventions for Typescript regarding types? I'm honestly struggling to find any consensus here.

I _do_ think it's correct to expose these types explicitly, but it's definitely not correct to have the consumer of the module reach into the typescript src for the types, because you run into issues where there are conflicts with your project's tsconfig and the module's (which is, I believe, is the reason for the error you reported).
